import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { OnboardingProvider } from "@/lib/context";
import { NextAuthProvider } from "@/providers/nextAuthProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Educacion App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NextAuthProvider>
          <OnboardingProvider>{children}</OnboardingProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
